import { Product } from '@/types'

export const demoProducts: Product[] = [
  {
    _id: 'demo-1',
    name: 'Blood FX',
    slug: { current: 'blood-fx' },
    price: 2800,
    previousPrice: 3500,
    shortDescription: 'Sangre artificial ultra-realista para efectos especiales de cine y teatro.',
    mainImage: 'https://picsum.photos/seed/blood-fx-1/400/400',
    isNew: false,
    isOnSale: true,
    isFeatured: true,
    stock: 15,
    tags: ['sangre', 'fx', 'cine'],
  },
  {
    _id: 'demo-2',
    name: 'Liquid Latex',
    slug: { current: 'liquid-latex' },
    price: 3200,
    shortDescription: 'Látex líquido profesional para la creación de heridas y texturas realistas.',
    mainImage: 'https://picsum.photos/seed/latex-pro/400/400',
    isNew: true,
    isOnSale: false,
    isFeatured: true,
    stock: 8,
    tags: ['latex', 'prosthetics', 'fx'],
  },
  {
    _id: 'demo-3',
    name: 'Scar Wax',
    slug: { current: 'scar-wax' },
    price: 1800,
    shortDescription: 'Cera moldeable para crear cicatrices y lesiones en piel con acabado profesional.',
    mainImage: 'https://picsum.photos/seed/scar-wax/400/400',
    isNew: false,
    isOnSale: false,
    isFeatured: false,
    stock: 20,
    tags: ['cicatrices', 'wax', 'prosthetics'],
  },
  {
    _id: 'demo-4',
    name: 'Fresh Wound Gel',
    slug: { current: 'fresh-wound-gel' },
    price: 2200,
    previousPrice: 2600,
    shortDescription: 'Gel transparente con pigmentos para simular heridas frescas con efecto tridimensional.',
    mainImage: 'https://picsum.photos/seed/wound-gel/400/400',
    isNew: true,
    isOnSale: true,
    isFeatured: true,
    stock: 12,
    tags: ['heridas', 'gel', 'fx'],
  },
  {
    _id: 'demo-5',
    name: 'Pro FX Palette',
    slug: { current: 'pro-fx-palette' },
    price: 8500,
    shortDescription: 'Paleta profesional con 24 colores para maquillaje FX de alto impacto.',
    mainImage: 'https://picsum.photos/seed/palette-fx/400/400',
    isNew: false,
    isOnSale: false,
    isFeatured: true,
    stock: 5,
    tags: ['paleta', 'profesional', 'fx'],
  },
  {
    _id: 'demo-6',
    name: 'Special Effects Kit',
    slug: { current: 'special-effects-kit' },
    price: 12000,
    shortDescription: 'Kit completo para efectos especiales: sangre, látex, cera y paleta de colores.',
    mainImage: 'https://picsum.photos/seed/sfx-kit/400/400',
    isNew: true,
    isOnSale: false,
    isFeatured: true,
    stock: 3,
    tags: ['kit', 'efectos', 'profesional'],
  },
  {
    _id: 'demo-7',
    name: 'Prosthetic Adhesive',
    slug: { current: 'prosthetic-adhesive' },
    price: 1500,
    shortDescription: 'Adhesivo de grado médico para la fijación de prótesis y piezas de espuma.',
    mainImage: 'https://picsum.photos/seed/adhesive/400/400',
    isNew: false,
    isOnSale: false,
    isFeatured: false,
    stock: 25,
    tags: ['adhesivo', 'prosthetics', 'profesional'],
  },
  {
    _id: 'demo-8',
    name: 'Aging & Wrinkle Set',
    slug: { current: 'aging-wrinkle-set' },
    price: 4200,
    shortDescription: 'Set completo para efectos de envejecimiento: arrugas, manchas y textura de piel envejecida.',
    mainImage: 'https://picsum.photos/seed/aging-set/400/400',
    isNew: true,
    isOnSale: false,
    isFeatured: false,
    stock: 7,
    tags: ['envejecimiento', 'arrugas', 'fx'],
  },
]

export const demoCategories = [
  { _id: 'cat-1', name: 'Sangre & Heridas', slug: { current: 'sangre-heridas' }, description: 'Efectos de sangre y heridas realistas' },
  { _id: 'cat-2', name: 'Prótesis & Látex', slug: { current: 'protesis-latex' }, description: 'Materiales para prótesis y trabajos en látex' },
  { _id: 'cat-3', name: 'Paletas & Colores', slug: { current: 'paletas-colores' }, description: 'Paletas profesionales de maquillaje FX' },
  { _id: 'cat-4', name: 'Kits & Sets', slug: { current: 'kits-sets' }, description: 'Kits completos para efectos especiales' },
  { _id: 'cat-5', name: 'Adhesivos', slug: { current: 'adhesivos' }, description: 'Adhesivos profesionales para maquillaje FX' },
  { _id: 'cat-6', name: 'Envejecimiento', slug: { current: 'envejecimiento' }, description: 'Técnicas y materiales de envejecimiento' },
]
